### ISSUE TITLE
Faster equality

### ISSUE THREAD

**Issue by oxinabox** [xiaodaigh/ShortStrings.jl#15]
It should be possible to massively speed up equality checks between ShortStrings.

For two short-strings we can just compare the number that is behind them

For a `ShortString` and an `AbstractString`
right now we convert the `ShortString` to a `String` then compare.
We should instead convert the `AbstractString` into a `ShortString` of the same type as the current one.
If it is short enough.
If it isn't short enough we know they are not equal

**Comment by xiaodaigh** [comment]
fixed by #16
