### ISSUE TITLE
Fast constructor for constructing a larger ShortString from a shorter one

### ISSUE THREAD

**Issue by oxinabox** [xiaodaigh/ShortStrings.jl#18]
I think there should be a fast way to convert one short string into another, larger one.
This would be useful for implementing cmp and for making promotion work

**Comment by xiaodaigh** [comment]
This already works after #25 and your PR earlier right? 

Re-open if I got this wrong

```
ss3"abc" == ss7"abc" # true
```

**Comment by oxinabox** [comment]
Oh yeah I forgot I opened ban issue about it.
